#!/usr/bin/env bash

# Script to get the Advent of Code input files
# Usage: ./get_inputs
source .env
mkdir -p data
current_date=$(date +%Y-%m-%d)
if [[ "${current_date}" > '2024-12-31' ]]
then
    current_date='2024-12-31'
fi
current_day=${current_date:8:2}
for day in $(seq -w 01 ${current_day}); do
    day_no_zeros=$(echo ${day} | sed 's/^0*//')
    puzzle_file="data/day_${day}.txt"
    if [[ -f "${puzzle_file}" ]]
    then
        echo "File ${puzzle_file} already exists."
    else
        curl "https://adventofcode.com/2024/day/${day_no_zeros}/input" \
        -H "cookie: session=${AOC_SESSION_COOKIE}" \
        -o "${puzzle_file}"
    fi
done
